version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: student_prep_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: student_prep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d student_prep"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local